"""Add created_by to Patient

Revision ID: 283b1a9abe6a
Revises: fc0670852c38
Create Date: 2025-07-21 02:24:27.532984

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '283b1a9abe6a'
down_revision: Union[str, Sequence[str], None] = 'fc0670852c38'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('patients', sa.Column('created_by', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'patients', 'users', ['created_by'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'patients', type_='foreignkey')
    op.drop_column('patients', 'created_by')
    # ### end Alembic commands ###
