"""edit phone_number on patients and description to diseases

Revision ID: fc0670852c38
Revises: 765140b7dd20
Create Date: 2025-07-13 13:48:12.856799

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'fc0670852c38'
down_revision: Union[str, Sequence[str], None] = '765140b7dd20'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('diseases', sa.Column('description', sa.Text(), nullable=False))
    op.drop_constraint(op.f('diseases_disease_name_key'), 'diseases', type_='unique')
    op.create_index(op.f('ix_diseases_name'), 'diseases', ['name'], unique=True)
    op.drop_constraint(op.f('diseases_doctor_id_fkey'), 'diseases', type_='foreignkey')
    op.create_foreign_key(None, 'diseases', 'users', ['doctor_id'], ['id'], ondelete='CASCADE')
    op.create_unique_constraint(None, 'patients', ['phone_number'])
    op.drop_constraint(op.f('users_email_key'), 'users', type_='unique')
    op.create_index(op.f('ix_users_email'), 'users', ['email'], unique=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_users_email'), table_name='users')
    op.create_unique_constraint(op.f('users_email_key'), 'users', ['email'], postgresql_nulls_not_distinct=False)
    op.drop_constraint(None, 'patients', type_='unique')
    op.drop_constraint(None, 'diseases', type_='foreignkey')
    op.create_foreign_key(op.f('diseases_doctor_id_fkey'), 'diseases', 'users', ['doctor_id'], ['id'])
    op.drop_index(op.f('ix_diseases_name'), table_name='diseases')
    op.create_unique_constraint(op.f('diseases_disease_name_key'), 'diseases', ['name'], postgresql_nulls_not_distinct=False)
    op.drop_column('diseases', 'description')
    # ### end Alembic commands ###
